version: "3.8"
services:
  postgres:
    image: postgres:10.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa_db
    networks:
      - bridged
    volumes:
     - ./db-data/:/var/lib/postgresql/data/

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - bridged

networks:
  bridged:
    driver: bridge
